### PR TITLE
Added `additionalTopLevelDomains` option that enables support for cus…

### LINKED ISSUE #29: Do not support some domains, like .cn, .lv, .shop
Hi, I just checked some TLD, such like .cn, .site, .lv, .inc, .ltd, .shop. all these failed for the reason "typo"

``` javascript
const { validate } = require('deep-email-validator');

async function Validate(email) {
    const res = await validate({
        email: email,
        sender: 'test@hotmail.com',
        validateRegex: true,
        validateMx: false,
        validateTypo: true,
        validateDisposable: true,
        validateSMTP: false,
    });
    console.log(email, res.valid, res.valid ? '': res.reason);
}

const emails = [
    'test@domain.cn', 
    'test@domain.de', 
    'test@domain.com', 
    'test@domain.site',
    'test@domain.lv',
    'test@domain.inc',
    'test@domain.ltd',
    'test@domain.store',
    'test@domain.shop'
];
emails.forEach(x => {
    Validate(x);
});
```

## result as
```
test@domain.cn false typo
test@domain.site false typo
test@domain.lv false typo
test@domain.inc false typo
test@domain.ltd false typo
test@domain.shop false typo
test@domain.de true
test@domain.com true
test@domain.store true
```

### PR DESCRIPTION
**Pull request by information-security**
…tom TLDs (Fixes #29).

### CODE REVIEW

**Comment by information-security** [comment]
@mfbx9da4 Could you please review/merge this PR?

**Comment by mfbx9da4** [comment]
LGTM thanks!

**Comment by mfbx9da4** [comment]
Need to get round to releasing

**Comment by information-security** [comment]
@mfbx9da4 Let me know if you needed any assistant to speed up the process.

**Pull request merged**
